# SAS TUTORIAL
1. [Lesson 1: Essentials](https://vle.sas.com/course/view.php?id=11088&section=3)
    1. [Basics](#basics)
    2. [Program Structure](#structure)
    3. [Program Syntax](#syntax)
2. [Lesson 2: Access Data](https://vle.sas.com/course/view.php?id=11088&section=4)
    1. [Understanding SAS Data](#understanding)
    2. [Accessing Data Through Libraries](#accessinglibraries)
    3. [Importing Data into SAS](#importingdata)
3. [Lesson 3: Explore Data](https://vle.sas.com/course/view.php?id=11088&section=5)
    1. [Exploring Data](#explore)
    2. [Filtering Rows](#filter)
    3. [Formatting Columns](#formatcols)
    4. [Sorting Data and Removing Duplicates](#sort)
4. [Lesson 4: Prepare Data](https://vle.sas.com/course/view.php?id=11088&section=6)
    1. [Reading & Filtering Data](#readfilter)
    2. [Computing New Columns](#newcols)
    3. [Conditional Processing](#condprocess)
5. [Lesson 5: Analyzing and Reporting on Data](https://vle.sas.com/mod/scorm/player.php?a=10989&currentorg=ORG-EPG1V2&scoid=25245)
    1. [Enhancing Reports with Titles, Footnotes, and Labels](#reports)
    2. [Creating Frequency Reports](#freqreports)
    3. [Creating Summary Reports and Data](#sumreports)
6. [Lesson 6: Exporting Results](https://vle.sas.com/mod/scorm/player.php?a=10992&currentorg=ORG-EPG1V2&scoid=25251)
    1. [Exporting Data](#exportdata)
    2. [Exporting Reports](#exportreports)
7. [Lesson 7: Using SQL](https://vle.sas.com/course/view.php?id=11088&section=9)
    1. [Using SQL in SAS](#sassql)
    2. [Joining Tables](#joins)

## [Lesson 1: Essentials](https://vle.sas.com/course/view.php?id=11088&section=3)
1. [Basics](#basics)
2. [Program Structure](#structure)
3. [Program Syntax](#syntax)

<a name='basics'></a>
## Basics

### SAS Interfaces
1. __SAS Studio__: web-based interface
2. __SAS Windowing Environment__: the interface that is part of SAS
3. __SAS Enterprise Guide__: runs locally and connects on a local or remote server

### Components
1. __Editor__: write and submit code
2. __Log__: view SAS messages
3. __Results and Output Data__: view results

_work.tableName_: table that was generated by the program

__SASHELP__ library: toy datasets to learn SAS.

When running a program or part of a program, check __Notes__ section on the __LOG__ tab.

In [ ]:
/* read the dataset on 'set' and create a copy named 'myclass' */
data myclass;
	set sashelp.class;
run;

/* print 'myclass' table */
proc print data=myclass;
run;

In [ ]:
# DATA STEP reads input source, makes a SAS table (copy) with a new column 

/* read 'sashelp.shoes' and make a copy named 'work.shoes' */
data work.shoes;
	set sashelp.shoes;
	/* calculate NetSales by using the Sales and Returns columns */
	NetSales=Sales-Returns;
run;

/* calculate the mean and sum rounded to 2 d.p. */
proc means data=work.shoes mean sum maxdec=2;
	/* use the variable NetSales */
	var NetSales;
	/* group data by region column */
	class region;
run;

<a name='structure'></a>
## Program Structure
* A sequence of __steps__
* Two kind of steps:
    1. __DATA__ step: reads data from an input source, process it, and create a SAS table
    2. __PROC__ step: **proc**edure, process the table in a predefined way (statistics, visualizations)
* Each step starts with the corresponding keyword <br>
    * `data myclass;`
    
    * `proc print data=myclass;`
* Most steps end with a `run;` statements and a few `proc` steps end with a `quit` statement.
* If no `run` statement is used, the keyword, i.e. `data` or `proc`, signifies the end of the current step and the start of the next one.
* __Global Statements__: can be outside `DATA` and `PROC` steps, usually define some option or setting for the SAS session (do not need a `run;` after them), `TITLE`, `OPTIONS`, `LIBNAME`, etc.

In [ ]:
# read 'sashelp.cars', make copy as 'mycars', calculate and add AvgMPG column
data mycars;
	set sashelp.cars;
	AvgMPG=mean(mpg_city, mpg_highway);
run;

# GLOBAL statement
title "Cars with Average MPG Over 35";
proc print data=mycars;
    # select columns for analysis
	var make model type avgmpg;
    # choose rows that satisfy the condition
	where AvgMPG > 35;
run;

# GLOBAL statement
title "Average MPG by Car Type";
# calculate the mean, min, max rounded in 1 d.p.
proc means data=mycars mean min max maxdec=1;
    # select variable for analysis
	var avgmpg;
    # group by 'type' column
	class type;
run;

# GLOBAL statement
title;

<a name='syntax'></a>
## Program Syntax
* __Comments__:
    1. Single line comment: `* this is a comment;`
    
    2. Multi-line comment: `/* this a a comment */` (Control + /)
* __Syntax Errors__: _WARNING_ or _ERROR_ message in the __LOG__

## [Lesson 2: Access Data](https://vle.sas.com/course/view.php?id=11088&section=4)
1. [Understanding SAS Data](#understanding)
2. [Accessing Data Through Libraries](#accessinglibraries)
3. [Importing Data into SAS](#importingdata)

<a name='understanding'></a>
## Understanding SAS Data

### Types of Data
* __SAS Table__ (dataset): structured data, `.sas7bdat`
    1. __Descriptor__: contains metadata (table name, # of rows, col names, etc.)
    2. __Data__: data values
    
    
* __Required col attributes__: 
    1. __Name__: 1-32 chars, start with letter or _
    2. __Type__: numeric (0-9, minus sign, decimal points, scientific notation) or char (letters, numbers, special chars, blanks)
    3. __Length__: # of bytes.
    
___SAS Dates___ are a particular type of __numeric__ value.


* __Missing values__
    1. __Blank__ is stored for a char missing value
    2. __.__ is stored for a numeric missing value

In [ ]:
/* create a report of the descriptor portion of the table */
PROC CONTENTS DATA=dataset;
RUN;

<a name='accessinglibraries'></a>
## Accessing Data Through Libraries

In [ ]:
/* create a report of the descriptor portion of the table */
# /home/u61494243/EPG1V2/data/ = WHERE data is (location)
# storm_summary.sas7bdat = WHAT data is (type)
PROC CONTENTS DATA='/home/u61494243/EPG1V2/data/storm_summary.sas7bdat';
RUN;

__SAS library__ includes both the ___location___ and ___type___ of data, so you can avoid hardcoding the filepath.
* `LIBNAME libref engine "path";`
    * `LIBNAME` is a __global statement__
    
    * `libref`: libraryName, max 8 chars
    
    * `engine`: set of instructions depending on the data type, defaults to `base` for reading SAS tables, `xlsx` for excel files
    
    * `path`: location
* `libref.tableName` for using the library
* A library remains active until `libref` is deleted

In [ ]:
/* create a library */
LIBNAME mylib base "s:/workshop/data";

/* use the library */
PROC CONTENTS data=mylib.class;
RUN;

/* delete library reference */
LIBNAME mylib clear;

`WORK` library
* temporary lib
* automatically defined at the start of a SAS session
* any contents in it are deleted at the end of the SAS session
* it is the default working library, i.e., if you do not type a name in front of a tableName, SAS will use `work`

`SASHELP` library
* includes sample data

In [ ]:
LIBNAME out "/home/u61494243/EPG1V2/output";

/* Create two new tables, first defaults at WORK, second at OUT */
DATA class_copy1 out.class_copy2;
	SET sashelp.class;
RUN;

When SAS session restarts, `libref`s are deleted (e.g. `OUT` library above), but the tables stay permanently. 

We just need to re-instate the `LIBNAME` statement.

In [ ]:
/* LIBNAME libref engine path */
LIBNAME xlclass xlsx "s:/workshop/data/class.xlsx";

/* OPTIONS option(s) */
# Enforces rules of SAS V7
# if there are spaces in headers, they will be replaced by underscores
# if char length > 32 it will be truncated, etc.
OPTIONS VALIDVARNAME=V7;

* __Excel workbook__ = a collection of tables.
* Good practice to always `LIBNAME libref CLEAR;` at the end; if it stays active will prevent others for accessing the file!

In [ ]:
/* define options and create library */
OPTIONS validvarname=v7;
LIBNAME xlclass xlsx "s:/workshop/data/class.xlsx"

/* read the `class_birthdate` worksheet */
PROC contents data=xlclass.class_birthdate;
RUN;

/* delete library reference */
LIBNAME xlclass CLEAR;

<a name='importingdata'></a>
## Importing Data Into SAS

### Importing Unstructured Data
* Must be converted into a structured format (unstructured data -> SAS table)

In [ ]:
PROC IMPORT DATAFILE='filePath' DBMS=fileType OUT=outputTable;
RUN;

/* overwrite the outputTable if it already exists */
PROC IMPORT DATAFILE='filePath' DBMS=fileType OUT=outputTable <REPLACE>;
/* by default it used the first 20 rows to make a structural guess, takes a number or MAX /*
    <GUESSINGROWS=n|MAX;>
RUN;

In [ ]:
/* read CSV file */
PROC IMPORT datafile='/home/u61494243/EPG1V2/data/storm_damage.csv' DBMS=csv
	OUT=storm_dmg REPLACE;
RUN;

PROC CONTENTS DATA=storm_dmg;

In [ ]:
/* read XLSX file */
PROC IMPORT datafile='/home/u61494243/EPG1V2/data/storm_damage.xlsx' DBMS=xlsx
	OUT=storm_dmg_xl REPLACE;
    /* specify which sheet */
    sheet=class_test;
RUN;

PROC CONTENTS DATA=storm_dmg_xl;

__XLSX engine__ (`LIBNAME`) vs __PROC IMPORT__
* `LIBNAME` reads directly from the file, so data is always current

* `PROC IMPORT` creates a copy of the file, thus, data must be reimported if it changes

In [ ]:
/* read data from a "|" delimited file */
proc import datafile='/home/u61494243/EPG1V2/data/np_traffic.dat'
			/* dlm=delimited */
			dbms=dlm
			out=traffic_data
			replace;
		guessingrows=max;
			/* define delimiter */
			delimiter="|";
			
proc contents data=traffic;			
run;

# [Lesson 3: Explore Data](https://vle.sas.com/course/view.php?id=11088&section=5)
1. [Exploring Data](#explore)
2. [Filtering Rows](#filter)
3. [Formatting Columns](#formatcols)
4. [Sorting Data and Removing Duplicates](#sort)

<a name='explore'></a>
## Exploring Data
* `PRINT`creates a listing of all data

* `MEANS` calculates summary stats (N, mean, stddev, min, max)

* `UNIVARIATE` calculates more detailed summary stats

* `FREQ` creates a frequency table for each column

In [ ]:
DATA storm_summary;
	set '/home/u61494243/EPG1V2/data/storm_summary.sas7bdat';
RUN;

/* list the first 10 rows */
PROC PRINT data=storm_summary (obs=10);
	/* subset columns */
	var  Season Name Basin MaxWindMPH MinPressure StartDate EndDate;
	
/* calculate summary stats */
PROC MEANS data=storm_summary;
	/* subset columns to analyze (must be numeric) */
	var  MaxWindMPH MinPressure;
	
/* calculate detailed summary stats */
PROC UNIVARIATE data=storm_summary;
	/* subset columns to analyze (must be numeric) */
	var  MaxWindMPH MinPressure;
	
/* generate frequency-table */
PROC FREQ data=storm_summary;
	/* subset columns to analyze (must be numeric) */
	TABLES Basin Type Season;
RUN;

In [ ]:
/* Writes to the SAS log a record of each output object that is created */
ODS TRACE ON;
/*  select 20 extreme obsevations instead of 5 */
PROC UNIVARIATE data=pg1.eu_occ nextrobs=10;
	var Camp;
/* turns off the writing of the trace record */
ODS TRACE OFF;

/* select the desired object */
ODS SELECT ExtremeObs;
/*  select 20 extreme obsevations instead of 5 */
PROC UNIVARIATE data=pg1.eu_occ nextrobs=10;
	var Camp;

<a name='filter'></a>
## Filtering Rows
* `WHERE expression;`
* `expression` = column operator value
* Operators: 
    * `=` or `EQ`
    
    * `^=` or `~=` or `NE`
    
    * `>` or `GT`
    
    * `<` or `LT`
    
    * `>=` or `GE`
    
    * `<=` or `LE`
* __Character values__: case sensitive, enclosed in double or single quotation marks
* __Numeric values__: not enclosed in quotation marks, standard values, no symbols
* __SAS Data Constant__: `'ddmmmyyyy'd';`
* Combine expressions using `AND` and `OR`

In [ ]:
proc PRINT data=pg1.storm_summary;
	WHERE StartDate >= "01JAN2010"d;
run;

In [ ]:
PROC PRINT data=sashelp.cars;
	/* define variables for analysis */
	VAR Make Model Type MSRP MPG_City MPG_Highway;
	/* define conditions */
	WHERE Type="SUV" AND MSRP <= 30000;
RUN;

* `WHERE col IN ("val1", "val2");`

* `WHERE col NOT IN ("val1", "val2"):`

In [ ]:
PROC PRINT data=sashelp.cars;
	/* define variables for analysis */
	VAR Make Model Type MSRP MPG_City MPG_Highway;
	/* define condition using multiple values */
	WHERE Type in ("SUV", "Truck", "Wagon");
RUN;

__Excluse Missing Values__

In [ ]:
proc PRINT data=pg1.storm_summary;
    /* NaNs are treated as the smallest possible value */
	WHERE MaxWindMPH > 156 OR 0< MinPressure < 920;
run;

### Special `WHERE` Operators
* __Missing Values__: 
    * `where col1=.;` or `where col1=" ";`
    
    * `where col1 IS MISSING;` or `where col1 IS NOT MISSING;` (both for num and char values)
    
    * `where col1 IS NULL;`
* __Ranges__:
    * `where col1 BETWEEN val1 AND val2;` (endpoints inclusive)
* __Pattern Matching__:
    * `where col1 LIKE "val";`
    
    * `%` wildcard (any number of chars)
    
    * `_` single char

In [ ]:
proc print data=pg1.storm_summary(obs=50);
	*where MinPressure is missing; /*same as MinPressure = .*/
	*here Type is not missing; /*same as Type ne " "*/
	*here MaxWindMPH between 150 and 155;
	*where Basin like "_I";
	where Name LIKE "Z%";
run;

### Creating and Using Macros
* Create the MV: `%LET mvName=val;` (not enclosed in quotes!)

* Use the MV: `"&mvName";` (double quotation marks only!!!!)
* MVs are temporary; they get deleted after the SAS session.

In [ ]:
/* define macro-variables (no quotes!) */
%LET WindSpeed = 156;
%LET BasinCode = NA;
%LET Date= 01JAN2000;

proc print data=pg1.storm_summary;
	/* use macro-variables (num no quotes, char+date double quotes) */
	where MaxWindMPH>=&WindSpeed and Basin="&BasinCode" and StartDate>="&Date"d;
	var Basin Name StartDate EndDate MaxWindMPH;
run;

proc means data=pg1.storm_summary;
	where MaxWindMPH>=&Windspeed and Basin="&BasinCode" and StartDate>="&Date"d;
	var MaxWindMPH MinPressure;
run;

In [ ]:
proc print data=pg1.np_traffic;
	/* select variables for listing */
	var ParkName Location Count;
	/* define conditions, upcase makes eliminates case sensitivity in char WHERE expressions*/
	where Count ^= 0 AND upcase(Location) LIKE '%MAIN ENTRANCE%';
RUN;

<a name='formatcols'></a>
## Formatting Columns
* format report values, e.g. `SALARY` from `6200` to `$6,200`

* `FORMAT colName desiredFormat` (it just changes the results tab, just the actual data)

* `<$(character)>formatName<width>.<digits>` (`.` required delimiter, `w`: total including decimals, chars)
    
* [format documentation](https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/leforinforref/n0p2fmevfgj470n17h4k9f27qjag.htm)

In [ ]:
proc print data=pg1.class_birthdate;
	/* format Height and Weight rounded to 3 ints max, and Birthdate as date9 */
	FORMAT Height Weight 3. Birthdate date9.;
RUN;

In [ ]:
***********************************************************;
*  Syntax and Example                                     *;
*                                                         *;
*    FORMAT col-name(s) format;                           *;
*                                                         *;
*    <$>format-name<w>.<d>                                *;
*                                                         *;
*    Common formats:                                      *;
*       dollar10.2 -> $12,345.67                          *;
*       dollar10.  -> $12,346                             *;
*       comma8.1   -> 9,876.5                             *;
*       date7.     -> 01JAN17                             *;
*       date9.     -> 01JAN2017                           *;
*       mmddyy10.  -> 12/31/2017                          *;
*       ddmmyy8.   -> 31/12/17                            *;
***********************************************************;

proc print data=pg1.class_birthdate;
	format Height Weight 3. Birthdate date9.;
run;	

proc print data=pg1.storm_damage;
	FORMAT Date MMDDYY10. Cost DOLLAR16.;
run;

In [ ]:
proc freq data=pg1.storm_summary order=freq;
	tables StartDate;
	/* format by month's name and also groups by month */
	FORMAT StartDate MONNAME.;
run;

<a name='sort'></a>
## Sorting Data and Removing Duplicates
* Improve visual arrangement of the data
* Identify and remove duplicates
* `PROC SORT DATA=inputTableName OUT=outputTableName BY <DESCENDING> colName;`

* If `OUT` is not specified, original data will be sorted!!!

* `PROC SORT` does not generate output, thus, `PROC PRINT DATA=outputTableName;`

In [ ]:
proc sort data=pg1.storm_summary out=STORM_SORT;
	where Basin in ('NA', 'na');
	by DESCENDING MaxWindMPH ;
	run;

proc print data=STORM_SORT;
run;

__Remove Duplicates__ (Adjacent rows -> SORT first)

In [ ]:
proc sort data=pg1.storm_summary out=STORM_SORT
		/* keeps only first occurence of each unique value */
		NODUPKEY DUPOUT=STORM_SORT_DUPS;
	where Basin in ('NA', 'na');
	by DESCENDING MaxWindMPH ;
	run;

proc print data=STORM_SORT;
run;

In [ ]:
proc sort data=pg1.storm_summary out=STORM_SORT
		/* DUPOUT table containts the removed rows */
		NODUPKEY DUPOUT=STORM_SORT_DUPS;
	/* removes entirely duplicated rows */
    BY _ALL_;
	run;

proc print data=STORM_SORT;
run;

In [ ]:
proc sort data=pg1.storm_summary out=STORM_SORT
		/* DUPOUT table containts the removed rows */
		NODUPKEY DUPOUT=STORM_SORT_DUPS;
	/* removes duplicated values on specified cols */
    BY colName;
	run;

proc print data=STORM_SORT;
run;

In [ ]:
/* keep only the specified columns */
proc sort data=pg1.eu_occ (KEEP=Geo Country) out=countrylist
		/* remove duplicate rows */
		NODUPKEY;
	BY Geo Country;

# [Lesson 4: Prepare Data](https://vle.sas.com/course/view.php?id=11088&section=6)
1. [Reading & Filtering Data](#readfilter)
2. [Computing New Columns](#newcols)
3. [Conditional Processing](#condprocess)

<a name='readfilter'></a>
## Reading & Filtering Data

In [ ]:
/* read original data and make a copy of it */
DATA tableCopied;
    SET originalTable;
RUN;

1. Compilation
2. Execution
    1. Read a single row from inputTable
    2. Sequentially process statements
    3. At `RUN;`, write the row to the outputTable
    4. Loop back to the top and read next row from inputTable

In [ ]:
**************************************************;
*  Read a SAS table and create a subset as new   *;
*  SAS table                                     *; 
**************************************************;

data myclass;
    set sashelp.class;
    where age >= 15;
run;

**************************************************;
*  Subset columns using the DROP or KEEP         *;
*  statements                                    *;
**************************************************;

data myclass;
    set sashelp.class;
    keep name age height;
    *drop sex weight;
run;

**************************************************;
*  Apply permanent formats using the             *;
*  FORMAT statements                             *;
*  (in PROC formats only results)                *;
**************************************************;

data myclass;
    set sashelp.class;
    format height 4.1 weight 3.;
run;

<a name='newcols'></a>
## Computing New Columns
### Feature Engineering 
`newCol = <expression>`

In [ ]:
data tropical_storm;
	set pg1.storm_summary;
	/* drop the specified columns */
	drop Hem_EW Hem_NS Lat Lon;
	/* filter rows */
	where Type="TS";
	/* create a new column */
	MaxWindKM = MaxWindMPH * 1.60934;
	/* round column to the nearest integer */
	format MaxWindKM 3.;
	/* create a new column */
	StormType= "Tropical Storm";
run;

In [ ]:
data storm_length;
	set pg1.storm_summary;
	drop Hem_EW Hem_NS Lat Lon;
	/* needs plus one !!! */
	StormLength = EndDate - StartDate+1;
run;

### Numeric Functions
`function(arg1, arg2)`
* `SUM()`
    
* `MEAN()`

* `MEDIAN()`

* `RANGE()`

* `MIN()`

* `MAX()`

* `N()` returns the number of non-missing numeric values

* `NMISS()` returns the number of missing numeric values

### Character Functions
* `UPCASE(char)`/`LOWCASE(char)` change letters in a char string to upper- or lower-case

* `PROPCASE(char, <delimiters>)` change str format to proper case

* `CATS(char1, char2)` concatenates char strings and removes leading and trailing blanks from each arg

* `SUBSTR(char, position, <length>)` returns a substring from a char string

* `SCAN(str, count)` returns the nth word from a character string.

### Date Functions

#### Extract info from SAS-dates
* `MONTH(SAS-date)` returns a number from 1-12 that represents the month

* `YEAR(SAS-date)` returns the 4-digit year

* `DAY(SAS-date)` returns a number from 1-31 that represents the day of the month

* `WEEKDAY(SAS-date)` returns a number from 1-7 that represents the day of the week (Sunday=1)

* `QTR(SAS-date)` returns a number from 1-4 that represents the quarter

#### Create SAS date values
* `TODAY()` returns the current date as a numeric SAS date value

* `MDY(month, day, year)` returns a SAS date value from numeric month, day, and year values

* `YRDIF(startdate, enddate, 'AGE')` calculates a precise age between two dates

In [ ]:
data storm_new;
	set pg1.storm_damage;
	drop Summary;
	/* 'AGE' is the basis that the cal is performed */
	YearsPassed = YRDIF(Date, TODAY(), 'AGE');
	/* extract the current year	*/
	Anniversary = mdy(MONTH(Date), day(date), year(today()));
	format YearsPassed 4.1 Date Anniversary mmddyy10.;
run;

<a name='condprocess'></a>
## Conditional Processing

`IF expression THEN statement`

In [ ]:
data storm_new;
	set pg1.storm_summary;
	keep Season Name Basin MinPressure PressureGroup;
	if MinPressure = . then PressureGroup = . ;
	/* without "0<" NaNs will be assigned group 1!!! */
	if 0 < MinPressure <= 920 then PressureGroup = 1;
	if MinPressure > 920 then PressureGroup = 0;
run;

`IF expression THEN statement;
<ELSE IF expression THEN statement;>
ELSE statement;`

In [ ]:
data storm_cat;
	set pg1.storm_summary;
	keep Name Basin MinPressure StartDate PressureGroup;
	*add ELSE keyword and remove final condition;
	if MinPressure=. then PressureGroup=.;
	ELSE IF MinPressure<=920 then PressureGroup=1;
	ELSE PressureGroup=0;
run;

#### Creating Char Cols
`LENGTH charColName $ length;`

In [ ]:
data storm_summary2;
	set pg1.storm_summary;
	/* create a char column of length 8 */
	length Ocean $ 8;
	keep Basin Season Name MaxWindMPH Ocean;
	Basin=upcase(Basin);
	OceanCode=substr(Basin,2,1);
	if OceanCode="I" then Ocean="Indian";
	else if OceanCode="A" then Ocean="Atlantic";
	else Ocean="Pacific";
run;

#### Multiple Statements with `IF-THEN/DO`

In [ ]:
data front rear;
    set sashelp.cars;
    if DriveTrain="Front" then do;
        DriveTrain="FWD";
        output front;
    end;
    else if DriveTrain='Rear' then do;
        DriveTrain="RWD";
        output rear;
    end;
run;

In [ ]:
data indian atlantic pacific;
	set pg1.storm_summary;
	length Ocean $ 8;
	keep Basin Season Name MaxWindMPH Ocean;
	Basin=upcase(Basin);
	OceanCode=substr(Basin,2,1);
    
	if OceanCode="I" then do;
		Ocean="Indian";
		output indian;
	end;
	else if OceanCode="A" then do;
		Ocean="Atlantic";
		output atlantic;
	end;
	else do;
		Ocean="Pacific";
		output pacific;
	end;
run;

`WHEN-DO`

In [ ]:
data parks monuments;
	set pg1.np_summary;
	where Type in ("NP", "NM");
	length ParkType $ 20;
	Campers = sum(RVCampers, TentCampers, BackcountryCampers, OtherCamping);
	format Campers comma17.;
	select (type);
		when ('NP') do;
			ParkType = "Park";
			output parks;
		end;
		otherwise do;
			ParkType = "Monument";
			output monuments;
		end;
	end;
	keep Reg ParkName DayVisits OtherLodging Campers ParkType;
run;

# [Lesson 5: Analyzing and Reporting on Data](https://vle.sas.com/mod/scorm/player.php?a=10989&currentorg=ORG-EPG1V2&scoid=25245)
1. [Enhancing Reports with Titles, Footnotes, and Labels](#reports)
2. [Creating Frequency Reports](#freqreports)
3. [Creating Summary Reports and Data](#sumreports)

<a name='reports'></a>
## Enchancing Reports with Titles, Footnotes and Labels

### Using Titles and Footnotes

In [ ]:
/* global statements */
/* define a title */
title "Class Report";
/* define a subtitle */
title2 "All Students";
/* define a footnote */
footnote "Report Generated by KSOR";

In [ ]:
/* clear titles and footnotes with a null title statement */
TITLE;
FOOTNOTE;

In [ ]:
title "Storm Analysis";

title2 "Summary Stats for MaxWind and MinPressure";
proc means data=pg1.storm_final;
	var MaxWindMPH MinPressure;
run;

/* this title replaces the title2 above */
title2 "Frequency Report for Basin";
proc freq data=pg1.storm_final;
	tables BasinName;
run;

### Using Macro Variables and Functions in Titles and Footnotes

In [ ]:
%let age=13;

title "Class Report";
/* Use macro variable in the title */
title2 "Age=&age";
footnote "School Use Only";

proc print data=pg1.class_birthdate;
	where age=&age;
run;

title;
footnote;

### Applying Temporary Labels to Columns

In [ ]:
proc means data=sashelp.cars;
	where type="Sedan";
	var MSRP MPG_Highway;
	/* add label column for better interpretation */
	label MSRP="Manufacturer Suggested Retail Price"
		  MPG="Highway Miles Per Gallon";
run;

Most `proc`s display `label`s automatically with the above way. `print` is an exception, but it can use `label`s as aliases.

In [ ]:
proc print data=sashelp.cars label;
	where type="Sedan";
	var Make Model MSRP MPG_Highway MPG_City;
	/* use aliases for better interpretation */
	label MSRP="Manufacturer Suggested Retail Price"
		  MPG_Highway="Highway Miles Per Gallon";
run;

### Segmenting Reports

In [ ]:
proc sort data=sashelp.cars
	out=cars_sort;
	/* group by the specified column */
	by Origin;
run;

/* create freq tables based on sorted tables */
proc freq data=cars_sort;
	by origin;
	tables Type;
run;

In [ ]:
proc sort data=pg1.storm_final out=storm_sort;
	where MaxWindMPH > 156;
	by BasinName descending MaxWindMPH;
run;

title "Category 5 Storms";
/* Use aliases and supress observation's column */
proc print data=storm_sort label NOOBS;
	var Season Name MaxWindMPH MinPressure StartDate StormLength;
	by BasinName;
	label MaxWindMPH="Max Wind (MPH)"
		MinPressure="Min Pressure"
		StartDate="Start Date"
		StormLength="Length of Storm (days)";
run;

/* clear title */
title;

### Applying Permanent Labels to Columns

In [ ]:
data=cars_update;
	set sashelp.cars;
	keep Make Model Type MSRP AvgMPG;
	AvgMPG=mean(MPG_Highway, MPG_City);
	/* if labels are added to the data step, they become permanent attributes*/
	label MSRP="Manufacturer Suggested Retail Price"
		  MPG="Highway Miles Per Gallon";
run;

<a name='freqreports'></a>
## Creating Frequency Reports
`proc freq data=dataset <proc options>;
    tables columName / options;
run`

In [ ]:
/* by def it is ordered alphabetically or sequenced */
/* order by desc freq and show "Number of Variable Levels" talbe */
proc freq data=pg1.storm_final order= freq nlevels;
	/* eliminate cumulative cols */
	tables BasinName Season / nocum;
run;

In [ ]:
/* by def it is ordered alphabetically or sequenced */
/* order by desc freq and show "Number of Variable Levels" talbe */
proc freq data=pg1.storm_final order= freq nlevels;
	/* eliminate cumulative cols */
	tables BasinName StartDate / nocum;
	/* "create" a month col to groupby */
	format StartDate monname.;
run;

In [ ]:
/* turn ODS graphics on */
ods graphics on;
/* remove procedure title */
ods noproctitle;
title "Frequency Report for Basin and Storm Month";
proc freq data=pg1.storm_final order= freq nlevels;
	/* eliminate cumulative cols, create freq plot */
	tables BasinName StartDate / nocum plots=freqplot(orient=horizontal scale=percent);
	/* "create" a month col to groupby */
	format StartDate monname.;
	label BasinName="Basin"
		  StartDate="Storm Month";
run;

title;
/* turn on for future programs */
ods proctitle;

In [ ]:
title "Frequency Report for Basin and Storm Month";

/* supress print */
proc freq data=pg1.storm_final order=freq noprint;
	tables StartDate / out= storm_count;
	format StartDate monname.;
run;

### Creating 2-way Frequency Reports
`TABLES colName*colName` <br>
TABLES rows\*columns (__crosstabulation report__)

Combination of columns.

In [ ]:
proc freq data=pg1.storm_final;
/* remove all default reporting but freq */
	tables BasinName*StartDate / norow nocol nopercent;
	format StartDate monname.;
	label BasinName="Basin"
		  StartDate="Storm Month";
run;

In [ ]:
proc freq data=pg1.storm_final;
/* default reports listed differently */
	tables BasinName*StartDate / crosslist;
	format StartDate monname.;
	label BasinName="Basin"
		  StartDate="Storm Month";
run;

In [ ]:
/* supress print */
proc freq data=pg1.storm_final noprint;
	/* put results in an output table */
	tables BasinName*StartDate / out=storm_counts;
	format StartDate monname.;
	label BasinName="Basin"
		  StartDate="Storm Month";
run;

In [ ]:
title "Selected Park Types by Region";
ods graphics on;
proc freq data=pg1.np_codelookup order=freq;
	tables Type*Region / nocol norow nopercent crosslist
		plots=freqplot(orient=horizontal groupBy=row scale=grouppercent);
	where Type in ("National Historic Site", "National Monument", "National Park");
run;

title;

`PROC SGPLOT`

In [ ]:
title1 'Counts of Selected Park Types by Park Region';
proc sgplot data=pg1.np_codelookup;
    where Type in ('National Historic Site', 'National Monument', 'National Park');
	/* The HBAR statement creates a horizontal bar chart with separate bars for each Region. */
	/* The GROUP= option segments each bar by the distinct values of Type. */
	/* SEGLABEL display labels on each segment of the bars */
    hbar region / group=type seglabel fillattrs=(transparency=0.5) dataskin=crisp;
	/* The KEYLEGEND statement customizes the appearance and position of the legend. */
    keylegend / opaque across=1 position=bottomright location=inside;
	/* The XAXIS statement adds reference lines on the horizontal axis. */
    xaxis grid;
run;

<a name='sumreports'></a>
## Creating Summary Reports and Data
`PROC MEANS DATA=tableName <stat-list>
    VAR colName;
    CLASS colName;
    WAYS n;
RUN;`

In [ ]:
/* add extra stats and customize display order, to nearest whole int */
proc means data=pg1.storm_final mean median min max maxdec=0; 
	var MaxWindMPH;
	/* group by colName or col combination, BY requires SORT before while CLASS not */
	class BasinName StormType;
	/* indicate the combinations of class columns to use */
	/*	0 = use 0 cols (stats based on entire table)
		1 = a seperate table for each col
		2 = combination of the 2 cols */
	ways ;
run;

### Creating an Output Summary Table
`OUTPUT OUT=tableName <statistic=colName>;`

In [ ]:
proc means data=pg1.storm_final noprint;
	var MaxWindMPH;
	class BasinName;
	ways 1;
	/* if mean=; takes the name of the var, i.e. MaxWindMPH */
	output out=wind_stats max=MaxWind mean=AvgWind;
run;

In [ ]:
**************************************************;
*  Creating a Report with PROC TABULATE          *;
**************************************************;

proc format;
    value count 25-high="lightsalmon";
    value maxwind 90-high="lightblue";
run;

title "Storm Summary since 2000";
footnote1 "Storm Counts 25+ Highlighted";
footnote2 "Max Wind 90+ Highlighted";

proc tabulate data=pg1.storm_final format=comma5.;
	where Season>=2000;
	var MaxWindMPH;
	class BasinName;
	class Season;
	table Season={label=""} all={label="Total"}*{style={background=white}},
		BasinName={LABEL="Basin"}*(MaxWindMPH={label=" "}*N={label="Number of Storms"}*{style={background=count.}} 
		MaxWindMPH={label=" "}*Mean={label="Average Max Wind"}*{style={background=maxwind.}}) 
		ALL={label="Total"  style={vjust=b}}*(MaxWindMPH={label=" "}*N={label="Number of Storms"} 
		MaxWindMPH={label=" "}*Mean={label="Average Max Wind"})/style_precedence=row;
run;
title;
footnote;

In [ ]:
proc means data=pg1.np_multiyr noprint;
	var Visitors;
	class Region Year;
	ways 2;
	output out=top3parks(drop=_freq_ _type_)
			/* sum total visitors */
			sum=TotalVisitors
			/* find the max of visitors */
			IDGROUP(max(Visitors)
			/* top 3 */
			out[3] 
			/* output columns for top 3 parks */
			(Visitors ParkName)=);
run;

# [Lesson 6: Exporting Results](https://vle.sas.com/mod/scorm/player.php?a=10992&currentorg=ORG-EPG1V2&scoid=25251)
1. [Exporting Data](#exportdata)
2. [Exporting Reports](#exportreports)

<a name='exportdata'></a>
## Exporting Data
`PROC EXPORT`

* __CSV__ (comma-seperated values)
* __TAB__ (tab-delimited values)
* __DLM__ (space-delimited)
* __XLSX__ (excel file)

In [ ]:
/* define the input table */
proc export data=sashelp.cars
	/* where to export the file (must be relative to SAS location */
	outfile="s:/workshop/output/cars.txt"
	/* how to format the output, replace if it already exists */
	dbms=tab replace;
run;

In [ ]:
/* create an xlsx-engine library named xlout */
libname xlout xlsx "/home/u61494243/EPG1V2/output/southpacific.xlsx";

/* use libref to export data */
data xlout.South_Pacific;
	set pg1.storm_final;
	where Basin="SP";
run;

proc means data=pg1.storm_final noprint maxdec=1;
	where Basin="SP";
	/* select variable for analysis */
	var MaxWindKM;
	/* group results by the defined variable */
	class Season;
	ways 1;
	/* create a temp table */
	output out=xlout.Season_Stats n=Count mean=AvgMaxWindKM max=StrongestWindKM;
run;

libname xlout clear;

<a name='exportreports'></a>
## Exporting Reports
`ODS <destination><destination-specifications>;
/* SAS code that produces output */
ODS <destination> CLOSE;`

* __ODS__ (Output Delivery System)
* SAS PROC &rarr; Output Object &rarr; ODS destination

### Exporting Results to CSV

In [ ]:
ods csvall file="path.csv";
proc print data=sashelp.cars noobs;
	/* specify the order and the format of the variables */
	var Make Model Type MSRP MPG_City MPG_Highway;
	format MRSP dollar8.;
run;
ods csvall close;

In [ ]:
/* list all available styles */
proc template;
	list styles;
run;

ods excel file="/home/u61494243/EPG1V2/output/wind.xlsx" style=sasdocprinter
	options(sheet_name='Wind Stats');
title "Wind Statistics by Basin";
ods noproctitle;

proc means data=pg1.storm_final min mean median max maxdec=0;
    class BasinName;
    var MaxWindMPH;
run;

/* rename the work sheet generated by proc sgplot */
ods excel options(sheet_name='Wind Distribution');
title "Distribution of Maximum Wind";
proc sgplot data=pg1.storm_final;
    histogram MaxWindMPH;
    density MaxWindMPH;
run;
 
title;  
ods proctitle;
ods excel CLOSE;

### Exporting Results to PowerPoint and Microsoft Word
`ODS POWERPOINT file="path.pptx" style=style;
/* SAS code */
ODS POWERPOINT CLOSE;`

`ODS RTF file="path.rtf" startpage=no;
/* SAS code */
ODS rtf CLOSE;`

In [ ]:
%let path=/home/u61494243/EPG1V2/output/;

ods rtf file="&path/pressure.rtf" startpage=no;

title "Minimum Pressure Statistics by Basin";
ods noproctitle;
proc means data=pg1.storm_final mean median min maxdec=0;
    class BasinName;
    var MinPressure;
run;

title "Correlation of Minimum Pressure and Maximum Wind";
proc sgscatter data=pg1.storm_final;
	plot minpressure*maxwindmph;
run;
title;  

ods rtf close;

### Exporting Results to PDF

In [ ]:
options orientation=landscape;
ods pdf file='/home/u61494243/EPG1V2/output/StormSummary.pdf' style=journal nobookmarkgen;
title1 "2016 Northern Atlantic Storms";

/* control the layout of multiple objects */
ods layout gridded columns=2 rows=1;
ods region;

proc sgmap plotdata=pg1.storm_final;
    *openstreetmap;
    esrimap url='http://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map';
    bubble x=lon y=lat size=maxwindmph / datalabel=name datalabelattrs=(color=red size=8);
    where Basin='NA' and Season=2016;
    keylegend 'wind';
run;

ods region;
proc print data=pg1.storm_final noobs;
	var name StartDate MaxWindMPH StormLength;
	where Basin="NA" and Season=2016;
	format StartDate monyy7.;
run;

ods layout end;
ods pdf close;

# [Lesson 7: Using SQL](https://vle.sas.com/course/view.php?id=11088&section=9)
1. [Using SQL in SAS](#sassql)
2. [Joining Tables](#joins)

<a name='sassql'></a>
## Using SQL in SAS
`PROC SQL; QUERY; QUIT;`

* Alternative to `DATA` step or certain `PROC` steps

`PROC PRINT` vs `PROC SQL`
1. `PRINT` seperates variables with __spaces__, while `SQL` does that with __commas__.

2. `PRINT` ends with `RUN`;. `SQL` ends with `QUIT`.

3. `SQL` alliws computed columns in the `SELECT` clause.

### Filtering and Sorting Output

In [ ]:
title "International Storm since 2000";
title2 "Category 5 (Wind > 156)";
proc sql;
/* proper case */
SELECT Season, propcase(Name) as Name, StartDate format=MMDDYY10., MaxWindMPH 
	FROM pg1.storm_final
	WHERE MaxWindMPH > 156 and Season > 2000
	ORDER BY MaxWindMPH desc, Name;
quit;

title;

### Creating and Deleting Tables

In [ ]:
proc sql;
create table work.myclass as 
    select Name, Age, Height
        from pg1.class_birthdate
        where age > 15
        order by Height, Age;
quit;

In [ ]:
proc sql;
    drop table work.myclass;
quit;

<a name='joins'></a>
## Joining Tables

### Creating Inner Joins

In [ ]:
proc sql;
select Season, Name, storm_summary.Basin, BasinName, MaxWindMPH
    from pg1.storm_summary inner join pg1.storm_basincodes
    on upcase(storm_summary.Basin) = storm_basincodes.Basin
    order by Season desc, Name;
quit;

### Using Table Aliases

In [ ]:
proc sql;
select Season, Name, ss.Basin, BasinName, MaxWindMPH 
    from pg1.storm_summary as ss inner join pg1.storm_basincodes as sb
		on upcase(ss.Basin) = sb.Basin
    order by Season desc, Name;
quit;

### `DATA` vs `PROC SQL`

`DATA`
* More control of reading, writing, and manipulating data
* Can create multiple tables in one step
* Includes looping and array processing

`PROC SQL`
* ANSI-standard language used by most dbs
* Code can be more streamlined
* Can manipulate, summarize, and sort data in one step